config/routes.rb
Rails.application.routes.draw do

  post 'reservations/:reservation_id/payment/new' => 'payment#checkout'

  post 'listings/search' => 'listings#search'

  post 'listings/autocomplete' => 'listings#autocomplete'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :listings do 
    resources :reservations, only: [:new, :create, :index]
  end
  resources :welcome
  resources :reservations do
   resources :payment, only: [:new]
 end


  resources :users, controller: "users", only: [:create, :index, :edit, :update] do
    resources :reservations, controller: "reservations", only: [:index, :show]
    resources :listings, controller: "listings", only: [:index, :show]
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "welcome#index", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'


  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :user
	belongs_to :listing
	has_one :payment

	validate :reserved? 
	validates :start_date, presence: true
	validates :end_date, presence: true

	def reserved?
		existing_reservations = Reservation.where(listing_id: self.listing.id)

	    existing_reservations.each do |r|
	      if (start_date..end_date).overlaps?(r.start_date..r.end_date)
	        errors.add(:checkin, "Those dates are booked.")
		  end
		end
	end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.where(user_id: params['user_id'])
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new

  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    start_date = params['reservation']['date'][0..9]
    end_date = params['reservation']['date'][13..23]
    start_date = Date.strptime(start_date, "%m/%d/%Y")
    end_date = Date.strptime(end_date, "%m/%d/%Y")

    num_days = (end_date - start_date).to_i
    listing = Listing.find(params['listing_id'])
    price = listing.price * num_days

    @reservation = Reservation.new(start_date: start_date, end_date: end_date, user_id: params['user_id'], listing_id: params['listing_id'], price: price)

    respond_to do |format|
      if @reservation.save
        # ReservationMailer.reservation_email(@reservation).deliver_now
        ReservationJob.perform_later(@reservation)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { redirect_to @reservation, notice: 'Reservation failed. Please try other dates.' }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:reservation)
    end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: @reservation, local: true) do |form| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.text_field :date, class: "daterange"%>
    <%= hidden_field_tag :user_id, "#{current_user.id}" %>
    <%= hidden_field_tag :listing_id, "#{@listing.id}" %>
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<div class="card-group">
  <% @reservations.each do |r| %>
  <% listing_id = r.listing_id %>
  <% listing = Listing.find(listing_id) %>
  <div class="card">
    <%= image_tag listing.images_urls[0], :class => "card-img-top"%>
    <div class="card-body">
      <h5 class="card-title"><%= listing.location %></h5>
      <p class="card-text"><%= r.start_date%> - <%= r.end_date%></p>
      <p class="card-text">$ <%= r.price%></p>
      <%= link_to 'Make Payment', new_reservation_payment_path(r.id) %>
    </div>
  </div>
  <% end %>
</div>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>
<% @reservation = Reservation.new %>
<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>